# Generated by Django 3.1.7 on 2022-02-04 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv_user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cv_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=15)),
                ('skill_level', models.SmallIntegerField()),
                ('skill_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avartar', models.ImageField(blank=True, default='morning.jpg', null=True, upload_to='')),
                ('fullname', models.CharField(max_length=30)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('profile_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objective_content', models.TextField()),
                ('Objective_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_title', models.CharField(max_length=10)),
                ('language_level', models.CharField(max_length=15)),
                ('language_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_company', models.CharField(max_length=50)),
                ('experience_position', models.CharField(max_length=40)),
                ('experience_details', models.TextField()),
                ('experience_start', models.DateField()),
                ('experience_end', models.DateField()),
                ('experience_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_school', models.CharField(max_length=50)),
                ('education_major', models.CharField(max_length=40)),
                ('education_start', models.DateField()),
                ('education_end', models.DateField()),
                ('education_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_title', models.CharField(max_length=40)),
                ('certification_time', models.DateField()),
                ('certification_details', models.TextField()),
                ('certification_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_title', models.CharField(max_length=40)),
                ('additional_details', models.TextField()),
                ('additional_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=40)),
                ('activity_start', models.DateField()),
                ('activity_end', models.DateField()),
                ('activity_position', models.CharField(max_length=50)),
                ('activity_details', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('activity_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_project.cv_user')),
            ],
        ),
    ]
