# Generated by Django 4.0 on 2021-12-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_choice_question_delete_employee_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=20)),
                ('mobile_number', models.PositiveIntegerField()),
                ('employee_title', models.CharField(max_length=10)),
            ],
        ),
    ]
